server:
  port: 9001

spring:
  application:
    name: INVENTORY-SERVICE
datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
jpa:
    database-platform: org.hibernate.dialect.H2Dialect

zipkin:
    base-url: http://127.0.0.1:9411/
     
